### ISSUE TITLE
install err on ledger nano s plus

### ISSUE THREAD

**Issue by tpkeeper** [Zondax/ledger-polkadot#187]
mac os 13.3.1
python 3.11.3
node v16.13.0
ledger nano s plus (firmware 1.1.0)

installer:
v20.9370.0
[installer_nanos_plus.sh](https://github.com/Zondax/ledger-polkadot/releases/download/v20.9370.0/installer_nanos_plus.sh)

```
Traceback (most recent call last):
  File "/Users/tpkeeper/.pyenv/versions/3.9.1/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/tpkeeper/.pyenv/versions/3.9.1/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/tpkeeper/.pyenv/versions/3.9.1/lib/python3.9/site-packages/ledgerblue/loadApp.py", line 253, in <module>
    loader.createApp(code_length, args.apiLevel, args.dataSize, paramsSize, args.appFlags, args.bootAddr|1)
  File "/Users/tpkeeper/.pyenv/versions/3.9.1/lib/python3.9/site-packages/ledgerblue/hexLoader.py", line 346, in createApp
    self.exchange(self.cla, 0x00, 0x00, 0x00, data)
  File "/Users/tpkeeper/.pyenv/versions/3.9.1/lib/python3.9/site-packages/ledgerblue/hexLoader.py", line 189, in exchange
    return self.scpUnwrap(bytes(self.card.exchange(apdu)))
  File "/Users/tpkeeper/.pyenv/versions/3.9.1/lib/python3.9/site-packages/ledgerblue/comm.py", line 157, in exchange
    raise CommException("Invalid status %04x (%s)" % (sw, possibleCause), sw, response)
ledgerblue.commException.CommException: Exception : Invalid status 6512 (Unknown reason)
```

:link: [zboto Link](https://app.clickup.com/t/8677yx0pr)

**Comment by ftheirs** [comment]
There were some changes in the SDK so the older version might/can not be installed. It will depend on several factors 😞 
You can try with the [latest release](https://github.com/Zondax/ledger-polkadot/releases/tag/v21.9391.1) and reopen the issue if you face any problem!
